apiVersion: v1
kind: Service
metadata:
  name: win11-clone-service
spec:
  type: NodePort
  selector:
    app: win11-clone
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080