name: Build Locally and Deploy to k3s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build local Docker image
        run: |
          sudo docker build -t win11-clone:${{ github.sha }} .
          
      - name: Load image into k3s cluster
        run: |
          sudo docker save win11-clone:${{ github.sha }} -o image.tar
          sudo k3s ctr images import image.tar
          
      - name: Deploy to k3s
        run: |
          # Apply the manifests from the k8s/ directory
          sudo /usr/local/bin/kubectl apply -f k8s/deployment.yaml
          sudo /usr/local/bin/kubectl apply -f k8s/service.yaml

          # Update the deployment with the new image tag
          sudo /usr/local/bin/kubectl set image deployment/win11-clone-deployment win11-clone-container=win11-clone:${{ github.sha }}

          # Verify the rollout completes successfully
          sudo /usr/local/bin/kubectl rollout status deployment/win11-clone-deployment
