name: Build Locally and Deploy to k3s

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build local Docker image
        run: |
          sudo docker build -t win11-clone:${{ github.sha }} .
          
      - name: Load image into k3s cluster
        run: |
          sudo docker save win11-clone:${{ github.sha }} -o image.tar
          sudo k3s ctr images import image.tar
          
      - name: Deploy to k3s
        run: |
          sudo /usr/local/bin/kubectl apply -f deployment.yaml
          sudo /usr/local/bin/kubectl apply -f service.yaml

          sudo /usr/local/bin/kubectl set image deployment/win11-clone-deployment win11-clone-container=win11-clone:${{ github.sha }}

          sudo /usr/local/bin/kubectl rollout status deployment/win11-clone-deployment
